In [4]:
import numpy as np
import nnfs # package by the book's author to generate random data
from nnfs.datasets import spiral_data
import matplotlib.pyplot as plt

In [24]:
# Dense layer

class Layer_Dense:
  
  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # initialize weights and biases
    self.weights = 0.01 * np.random.rand(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
    
    
  # Forward pass
  
  def forward(self, inputs):
    # calculating the dot product
    self.output = np.dot(inputs, self.weights) + self.biases
    
    
# Relu activation
class Activation_Relu():
  
  # Forward pass
  def forward(self, inputs):
    # calculate output value from inputs
    self.output = np.maximum(0, inputs) # return value if its > 0 else 0 in the same shape as inputs
    
  


# Softmax activation
class Activation_Softmax():
  
  # forward pass
  def forward(self, inputs):
    
    # get unnormalized probabilities
    exp_values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
    
    # normalizing the probabilities
    probabilities = exp_values / np.sum(exp_values, axis = 1, keepdims = True)
    
    self.output = probabilities
    

In [46]:
# creating dataset
X, y = spiral_data(samples = 100, classes = 3)

# creating a dense layer with 2 input and 3 output values
dense1 = Layer_Dense(2, 3)

# creating a relu activation which will be used with dense layer
activation1 = Activation_Relu()

# create a second dense layer with 3 input features ( as we take output from the previous layer) and 3 output values
dense2 = Layer_Dense(3,3)

# create a softmax activation to be used with the dense layer
activation2 = Activation_Softmax()

# make a forward pass through the training data
dense1.forward(X)

# make a forward pass to activation function which takes the output of the first dense layer
activation1.forward(dense1.output)

# make a forward pass through the second dense layer which takes outputs from the previous activation function 
dense2.forward(activation1.output)

# make a forward pass through the second activation function which takes the inputs as outputs from the second dense layer
activation2.forward(dense2.output)


# Checkign the results

In [41]:
# The results is as expected, since we have 3 classes in our data, it predicts a value to be in any of those 3 classes equally at 33%, to make it better
# we need to tell the network how badly it had predicted the value to be so it can adjust it's weights and biases

In [47]:
print(activation2.output[:5])

[[0.33333333 0.33333333 0.33333333]
 [0.3333334  0.33333337 0.33333323]
 [0.33333346 0.33333341 0.33333313]
 [0.33333352 0.33333344 0.33333303]
 [0.33333344 0.33333339 0.33333317]]
