In [1]:
import numpy as np

In [54]:
# Using only Python

inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]


weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

           
biases = [2.0, 3.0, 0.5]


layer_outputs = []

# for each neuron
for neuron_weights, neuron_bias in zip(weights, biases): 
  # for each list of input
  for each_input in inputs:
    neuron_output = 0
    # for each input and weight to the neuron
    for n_input, weight in zip(each_input, neuron_weights): 
      # multiply the input for each associated weight
      # and add to the neuron's output variable
      neuron_output += n_input * weight
    # add bias
    neuron_output += neuron_bias
    # put neurons result to the layer's output
    layer_outputs.append((neuron_output))

print(f"Python output \n{layer_outputs}")

# shaping it with numpy to match the input structure
print(f"Reshaped result \n{np.reshape(np.expand_dims(np.array(layer_outputs), axis = 0), (3,3)).T}")

Python output 
[4.8, 8.9, 1.4100000000000001, 1.21, -1.8099999999999996, 1.0509999999999997, 2.385, 0.19999999999999996, 0.025999999999999912]
Reshaped result 
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [55]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]


weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

           
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(inputs, np.array(weights).T) + biases

print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
